Algoritmo "pag48Exercicio"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/10/2023
Var
// Seção de Declarações das variáveis 
a, b, c : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 a<-5
 b<-30
 c<-a
 a<-b
 b<-c
 
 escreval(a)
 escreval(b)
 escreval(c)
 
Fimalgoritmo